fix: #[internal_api] rejects pub items instead of panicking (#3337)
## What changes are proposed in this pull request?

This code:
```rust
#[internal_api]
pub struct Foo;
```

Caused the proc macro to panic, producing an unhelpful compiler
diagnostic:
```
error: custom attribute panicked
  --> kernel/src/lib.rs:306:1
   |
306 | #[internal_api]
   | ^^^^^^^^^^^^^^^
   |
   = help: message: unexpected token
```

Cause: Premature error handling in the macro's internals. 

With this fix, the intended diagnostic surfaces correctly:
```
error: ineligible for #[internal_api]: item is already public
  --> kernel/src/lib.rs:307:1
    |
307 | pub struct Foo;
    | ^^^
```

## How was this change tested?

Manually, see above.