chore: fix new warnings from clippy upgrade (#3164)
## What changes are proposed in this pull request?

Fix clippy warning:

```
Error:    --> kernel/src/expressions/sql.rs:330:10
    |
330 |         .chunks_exact(2)
    |          ^^^^^^^^^^^^^^^ help: consider using `as_chunks` instead: `as_chunks::<2>().0.iter()`
```

and unused imports.

## How was this change tested?

Existing tests/CI